### ISSUE TITLE
 https://pypi.org/project/sparse-dot-topn/

### ISSUE THREAD

**Issue by aradzhabov** [ing-bank/sparse_dot_topn#31]
Hello, thank you for the nice lib! 
This is not a bug but the following could confuse:
Description here -> https://pypi.org/project/sparse-dot-topn/
says pip install sparse-dot-topn 
'-' vs '_'
but all other docs including your project says pip install sparse_dot_topn

Thank you!
Alex

**Comment by ymwdalex** [comment]
@aradzhabov Hi Alex, thanks for your feedback. As you said, everywhere is sparse_dot_topn in the document and in the code. I think it is because python/pypi normalized the name and change '_' to '-',  according to this discussion.  https://groups.google.com/forum/#!topic/comp.lang.python/Y5zcSR7wn7c

I just test `pip install sparse_dot_topn` and `pip install sparse-dot-topn`, both of them can work.

Also from PEP, dash is not recommended to use as a package identifier. This stackoverflow has some discussion https://stackoverflow.com/questions/8350853/how-to-import-module-when-module-name-has-a-dash-or-hyphen-in-it

Best regards,
Zhe

**Comment by aradzhabov** [comment]
@ymwdalex Hi The, thank you for the clarification!!
