### ISSUE TITLE
unable to install on linux with arm platform

### ISSUE THREAD

**Issue by asiunov** [ing-bank/sparse_dot_topn#76]
```
$ pip3 install sparse-dot-topn==0.3.3
...
ERROR: Could not find a version that satisfies the requirement sparse-dot-topn==0.3.3 (from versions: 0.2, 0.2.1, 0.2.2, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.2.8, 0.2.9, 0.3.0, 0.3.1)
ERROR: No matching distribution found for sparse-dot-topn==0.3.3
```

If I understand correctly, this is because starting 0.3.2 the source package is not delivered to pypi repository and there is no binary for this OS and architecture combination.

```
$ python3
>>> import sysconfig; sysconfig.get_platform()
'linux-aarch64'
>>> from pip._vendor.packaging.tags import platform_tags; list(platform_tags())
['manylinux_2_31_aarch64', 'manylinux_2_30_aarch64', 'manylinux_2_29_aarch64', 'manylinux_2_28_aarch64', 'manylinux_2_27_aarch64', 'manylinux_2_26_aarch64', 'manylinux_2_25_aarch64', 'manylinux_2_24_aarch64', 'manylinux_2_23_aarch64', 'manylinux_2_22_aarch64', 'manylinux_2_21_aarch64', 'manylinux_2_20_aarch64', 'manylinux_2_19_aarch64', 'manylinux_2_18_aarch64', 'manylinux_2_17_aarch64', 'manylinux2014_aarch64', 'linux_aarch64']
```

**Comment by stephanecollot** [comment]
Could you tell us which version of python you are using?

**Comment by asiunov** [comment]
python 3.9.9
pip 22.0.4

**Comment by ymwdalex** [comment]
Thanks for your feedback @asiunov!

Since v0.3.2, we employed [cibuildwheels](https://github.com/pypa/cibuildwheel) to generate wheels for different OS and arch.

Unfortunately, we met some problems when we build wheels on Linux ARM. You can see this [comments](https://github.com/ing-bank/sparse_dot_topn/blob/master/.github/workflows/wheels.yml#L21). At that time, we didn't know how to solve the issue, so we skipped that Linux ARM wheel build.

@asiunov, if you would like to chip in this issue and do some investigation why sparse_dot_topn cibuildwheels doesn't work, we will be very appreciated.

**Comment by RUrlus** [comment]
@ymwdalex there is no tarball with the source files for >= 0.3.2 Most packages include source files alongside the wheels such that people on platforms/archs for which there are no wheels can compile/install themselves.

`pip install sparse-dot-topn --no-binary=sparse-dot-topn` grabs 0.3.1
